name: GHCR cleanup

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

permissions:
  packages: write
  contents: read

jobs:
  prune-untagged:
    runs-on: ubuntu-latest
    steps:
      - uses: dataaxiom/ghcr-cleanup-action@v1.2.2
        continue-on-error: true
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          packages: avianvisitors
          delete-untagged: true
